name: Run Linter And FastAPI Tests

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up uv
      uses: astral-sh/setup-uv@v3
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: uv sync --group test --group lint

    - name: Check formatting
      run: uv run ruff format --check

    - name: Run Ruff lint
      run: uv run ruff check

    - name: Start FastAPI server
      run: |
        uv run uvicorn main:app --host 127.0.0.1 --port 8000 &
        for i in {1..10}; do
          if nc -z 127.0.0.1 8000; then
            break
          fi
          echo "Waiting for the server to start..."
          sleep 2
        done

    - name: Run tests
      run: |
        uv run pytest

    - name: Stop FastAPI server
      run: |
        pkill uvicorn